#!/usr/bin/env python3
"""Attempt to mock jupyterlab launch."""

import json
import os
from pathlib import Path

import httpx
import respx
from jupyterlab.browser_check import BrowserApp


@respx.mock
def _mock_discovery() -> None:
    disco = json.loads(
        (
            Path(__file__).parent.parent
            / "data"
            / "etc"
            / "nublado"
            / "discovery_v1.json"
        ).read_text()
    )
    url = os.environ.get("REPERTOIRE_BASE_URL")
    if url is None:
        raise RuntimeError("REPERTOIRE_BASE_URL must be set")
    mocked = respx.get(url + "/discovery")
    mocked.return_value = httpx.Response(200, json=disco)

    # This doesn't work; instead, jupyterlab.browser_check() (called
    # by BrowserApp.launch_instance() ) gives me a KeyError, and apparently
    # it's being used in the Extension Manager's extension_points
    # starter_extension list.
    #
    # I don't yet know how to correctly mock this out with respx, hence
    # the use of the _INTEGRATION_TESTING flag in the RSP client.
    BrowserApp.launch_instance()


if __name__ == "__main__":
    _mock_discovery()
