#!/usr/bin/env python3
"""Fake 'typst' command for testing."""

import sys
from pathlib import Path


def usage() -> None:
    """Print usage."""
    print(f"Usage: {sys.argv[0]} compile file.typ\n", file=sys.stderr)


def main() -> None:
    """Pretend to compile .typ to .pdf."""
    if (
        len(sys.argv) != 3
        or sys.argv[1] != "compile"
        or not sys.argv[2].endswith(".typ")
    ):
        usage()
        sys.exit(1)

    basename = sys.argv[2][: -len(".typ")]
    pdf = basename + ".pdf"
    Path(pdf).write_text("Ceci pas un PDF document.")


if __name__ == "__main__":
    main()
