name: CI

"on":
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "renovate/**"
      - "tickets/**"
      - "u/**"
    tags:
      - "*"
  pull_request: {}

jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Install tox
        run: pip install tox

      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ matrix.python }}-${{ hashFiles('package.json') }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tox-${{ matrix.python }}-${{ hashFiles('package.json') }}-

      - name: Run tox
        run: tox -e py,coverage-report,typing

  pypi:

    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Build and publish
        uses: lsst-sqre/build-and-publish-to-pypi@v1
        with:
          pypi-token: ${{ secrets.PYPI_SQRE_ADMIN }}
          python-version: "3.10"
          run: |
            pip install 'jupyterlab<4'
            jlpm add rimraf
            jlpm build:prod
            python setup.py sdist bdist_wheel --universal
          upload: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

